Remove XAPPS flag verification
- Instead, echo ro.xosp.apps=true to build.prop to make the user know from About Phone that he/she got the apps installed

Signed-off-by: Calin <nilac8991@gmail.com>

diff --git a/Script/META-INF/com/google/android/update-binary b/Script/META-INF/com/google/android/update-binary
--- a/Script/META-INF/com/google/android/update-binary
+++ b/Script/META-INF/com/google/android/update-binary
@@ -176,6 +176,8 @@ ZIP=$3
 
 echo -n -e "ui_print $1\n" > /proc/self/fd/$OUTFD
 echo -n -e "ui_print\n" > /proc/self/fd/$OUTFD
+echo "#Make the user know that he got the XOSPApps installed" >> /system/build.prop
+echo "ro.xosp.apps=true" >> /system/build.prop
 sed -i '/deep_buffer {/,/}/d' /system/etc/audio_policy.conf
 
 }
@@ -264,33 +266,23 @@ if [ -z "$BIN" ]; then
 fi
 
 
-XAPPS=$(grep_prop ro.xosp.apps | cut -c-4)
 REL=$(grep_prop ro.xosp.release | cut -c-3)
 REV=$(grep_prop ro.xosp.revision | cut -c-9)
 
-XEAPPS=false
 DEFAULT=true
 
-if [ "$XAPPS" = "true" ]; then XEAPPS=true; fi;
-
-if [ "$XEAPPS" = "$DEFAULT" ]; then
-  ui_print "[OK] You're on XOSP" 
-    if [ "$REL" = "$DEFREL" ]; then
-      ui_print "[OK] You're on $DEFREL"
-        if [ "$REV" = "$DEFREV" ]; then
-          ui_print "[OK] You're on $DEFREV"
-          else 
-            ui_print "[FAIL] You're not on $DEFREV! Aborting..."
-            exit 1
-          fi
-        else 
-          ui_print "[FAIL] You're not on $DEFREL! Aborting..."
-          exit 1
+  if [ "$REL" = "$DEFREL" ]; then
+    ui_print "[OK] You're on $DEFREL"
+      if [ "$REV" = "$DEFREV" ]; then
+        ui_print "[OK] You're on $DEFREV"
+      else 
+        ui_print "[FAIL] You're not on $DEFREV! Aborting..."
+        exit 1
         fi
-else 
-  ui_print "[FAIL] You're not on XOSP! Aborting..."
-  exit 1
-fi
+  else 
+    ui_print "[FAIL] You're not on $DEFREL! Aborting..."
+    exit 1
+  fi
 
 if [ -z "$BIN" ]; then
   ui_print "[OK] Files Extracted!" 
